// images.js
const images = {
  // Finish Swatches
  finish03: require("./images/03.png"),
  finish04: require("./images/04.png"),
  finish09: require("./images/09.png"),
  finish10: require("./images/10.png"),
  finish10B: require("./images/10B.png"),
  finish10BE: require("./images/10BE.png"),
  finish10BL: require("./images/10BL.png"),
  finish14: require("./images/14.png"),
  finish15: require("./images/15.png"),
  finish20D: require("./images/20D.png"),
  finish26: require("./images/26.png"),
  finish26D: require("./images/26D.png"),
  finish32: require("./images/32.png"),
  finish32D: require("./images/32D.png"),
  finishBSP: require("./images/BSP.png"),
  finishWSP: require("./images/WSP.png"),

  // Standard levers
  LeverA: require("./images/LeverA.png"),
  LeverB: require("./images/LeverB.png"),
  LeverE: require("./images/LeverE.png"),
  LeverF: require("./images/LeverF.png"),
  LeverJ: require("./images/LeverJ.png"),
  LeverL: require("./images/LeverL.png"),
  LeverP: require("./images/LeverP.png"),
  LeverW: require("./images/LeverW.png"),

  // Coastal Series Levers
  LeverR: require("./images/LeverR.png"),
  LeverS: require("./images/LeverS.png"),
  LeverY: require("./images/LeverY.png"),
  LeverG: require("./images/LeverG.png"),

  // Centro Series Levers
  LeverMD: require("./images/LeverMD.png"),
  LeverMJ: require("./images/LeverMJ.png"),
  LeverMP: require("./images/LeverMP.png"),
  LeverND: require("./images/LeverND.png"),
  LeverNJ: require("./images/LeverNJ.png"),

  // Notting Hill Series Levers
  LeverMA: require("./images/LeverMA.png"),
  LeverMQ: require("./images/LeverMQ.png"),
  LeverMT: require("./images/LeverMT.png"),
  LeverMO: require("./images/LeverMO.png"),
  LeverMZ: require("./images/LeverMZ.png"),
  LeverGT: require("./images/LeverGT.png"),

  // Aventura Series Levers
  LeverMB: require("./images/LeverMB.png"),
  LeverME: require("./images/LeverME.png"),
  LeverMF: require("./images/LeverMF.png"),
  LeverNF: require("./images/LeverNF.png"),
  LeverMG: require("./images/LeverMG.png"),
  LeverMI: require("./images/LeverMI.png"),
  LeverMW: require("./images/LeverMW.png"),

  // Odeon Series Levers
  LeverMN: require("./images/LeverMN.png"),
  LeverMH: require("./images/LeverMH.png"),
  LeverMS: require("./images/LeverMS.png"),
  LeverMU: require("./images/LeverMU.png"),
  LeverMV: require("./images/LeverMV.png"),
  LeverNU: require("./images/LeverNU.png"),
  LeverWG: require("./images/LeverWG.png"),

  // Gramercy Series
  LeverRCM: require("./images/LeverRCM.png"),
  LeverRAL: require("./images/LeverRAL.png"),
  LeverREM: require("./images/LeverREM.png"),
  LeverRAM: require("./images/LeverRAM.png"),
  LeverRAS: require("./images/LeverRAS.png"),
  LeverRAG: require("./images/LeverRAG.png"),
  LeverRGM: require("./images/LeverRGM.png"),
  LeverRAW: require("./images/LeverRAW.png"),
  LeverH015: require("./images/LeverH015.png"),
  LeverH016: require("./images/LeverH016.png"),
  LeverH017: require("./images/LeverH017.png"),
  LeverH018: require("./images/LeverH018.png"),

  // Wooster Series
  LeverH001: require("./images/LeverH001.png"),
  LeverH002: require("./images/LeverH002.png"),
  LeverH003: require("./images/LeverH003.png"),
  LeverH004: require("./images/LeverH004.png"),
  LeverH005: require("./images/LeverH005.png"),
  LeverH006: require("./images/LeverH006.png"),
  LeverH007: require("./images/LeverH007.png"),
  LeverH008: require("./images/LeverH008.png"),
  LeverH011: require("./images/LeverH011.png"),

  // 10x indicator lever (VSLL)
  LeverVSLLWhite: require("./images/LeverVSLL.png"),
  LeverVSLLGreen: require("./images/LeverVSLL.png"),

  // pulls
  PullFLL: require("./images/PullFLL.png"),
  PullPTB: require("./images/PullPTB.png"),
  PullFLW: require("./images/PullFLW.png"),
  PullMAL: require("./images/PullMAL.png"),
  PullSTS: require("./images/PullSTS.png"),
  Pull862: require("./images/Pull862.png"),
  Pull863: require("./images/Pull863.png"),
  Pull864: require("./images/Pull864.png"),

  // Escutcheon Trims
  ET700: require("./images/700ET.png"),
  ES700: require("./images/700ES.png"),
  ER700: require("./images/700ER.png"),
  P700WE: require("./images/P700 WE.png"),
  P700NE: require("./images/P700 NE.png"),

  logo: require("./images/Sargent Logo.jpg"),
  UnderConstruction: require("./images/Construction.gif"),
  stop: require("./images/stop.jpg"),

  ORose: require("./images/ORose.png"),
  CORose: require("./images/CORose.png"),
  LNRose: require("./images/LNRose.png"),
  TRRose: require("./images/TRRose.png"),
  CRRose: require("./images/CRRose.png"),
  LRose: require("./images/LRose.png"),
  TORose: require("./images/TORose.png"),
  TEEsc: require("./images/TEEsc.png"),
  CEEsc: require("./images/CEEsc.png"),
  E2Rose: require("./images/E2Rose.png"),
  E3Rose: require("./images/E3Rose.png"),
  E4Rose: require("./images/E4Rose.png"),
  ERose: require("./images/ERose.png"),
  LE1Esc: require("./images/LE1Esc.png"),
  LE3Esc: require("./images/LE3Esc.png"),
  LW1Esc: require("./images/LW1Esc.png"),
  LSEsc: require("./images/LSEsc.png"),
  VN1Esc: require("./images/VN1Esc.png"),
  WTEsc: require("./images/WTEsc.png"),

  //Strikes
  StrikeC908: require("./images/C908Strike.png"),
  Strike815: require("./images/815Strike.png"),
  Strike650: require("./images/650Strike.png"),
  Strike606: require("./images/606Strike.png"),
  Strike624: require("./images/624Strike.png"),
  Strike640: require("./images/640Strike.png"),
  Strike646: require("./images/646Strike.png"),
  Strike648: require("./images/648Strike.png"),
  Strike649: require("./images/649Strike.png"),
  Strike64988: require("./images/64988Strike.png"),
  Strike658: require("./images/658Strike.png"),
  Strike657: require("./images/657Strike.png"),
  Strike653: require("./images/653Strike.png"),
  Strike655: require("./images/655Strike.png"),
  Strike642: require("./images/642Strike.png"),
  Strike644: require("./images/644Strike.png"),
  Strike613: require("./images/613Strike.png"),
  MortiseCL: require("./images/MortiseCLStrike.png"),
  Strike877: require("./images/877OBStrike.png"),
  Strike800: require("./images/800Strike.png"),
  Strike80011: require("./images/11Line800Strike.png"),
  Strike505: require("./images/505Strike.png"),
  Strike808: require("./images/808Strike.png"),
  Strike80811: require("./images/11Line808Strike.png"),
  Strike654: require("./images/654Strike.png"),
  Strike656: require("./images/656Strike.png"),
  Strike659: require("./images/659Strike.png"),
  StrikeWBS: require("./images/WBStrike.png"),
  StrikeDBS: require("./images/DBStrike.png"),
  Strike9200DBS: require("./images/9200DBStrike.png"),
};

export default images;
